### ISSUE TITLE
No indentation in code

### ISSUE THREAD

**Issue by Poonam-Singh-Bagh** [navgurukul/soni-sori#187]
There is no indentation in code.

![WhatsApp Image 2021-12-14 at 4 08 51 PM](https://user-images.githubusercontent.com/67674096/145985333-ac432993-7cc9-4cbf-a47a-2414e53997b2.jpeg)
![WhatsApp Image 2021-12-14 at 4 08 50 PM](https://user-images.githubusercontent.com/67674096/145985349-06a5e9db-82a7-4bfd-91e0-603d8fd68439.jpeg)

**Comment by saquibaijaz** [comment]
Indentation fixed.
But now embedded code editor is implemented.
