### ISSUE TITLE
(Student) Residential Programs and Miscellaneous Courses options are not available

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#207]
**Describe the bug**
Residential Programs and Miscellaneous Courses options are not available on app

**To Reproduce**
1. Student logs in the app using google
2. The Learning track has only four options
3. Residential Programs and Miscellaneous Courses options are not available

**Expected behaviour**
All six options should be present in the learning track

**Screencast**
https://drive.google.com/file/d/1M3Oq_4GKDCRDmHhohvvSAoHoqqQYNHKq/view

**Refer Sheet:**
Student is logged in (app), Test Case 1.2

**Comment by Dhan-shri** [comment]
Hey Saquib I discussed with Backend and frontend team that Miscellaneous courses are not part of our pathway, they are just keep for campuses only in web, can you just confirm with Narendra regarding this as he knows better about this than me.

**Comment by saquibaijaz** [comment]
@Dhan-shri
Need five learning tracks on the app
English, Python, Typing, JavaScript, Residential
