### ISSUE TITLE
The laerning tracks redirect to non relevant screens

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#208]
**Describe the bug**
The Learning Tracks, when tapped, redirects to non relevant pages

**To Reproduce**
1. Student taps on JavaSvript
2. Student is taken to Spoken English Screen
3. Student taps on Spoken English
4. Student is taken to Residential Programmes screen

**Expected behaviour**
Tapping on any of the Learning Tracks should take the student to their relevant screen

**Screencast**
1. https://drive.google.com/file/d/1M5sh_7TL6b7U7mw_OWXM68Bww1NxLeOo/view
2. https://drive.google.com/file/d/1M4hxnGL7DOn00m3I0V_VvaGV4XS2ih7C/view

**Refer Sheet:**
Student is logged in (app), Test Cases 2.2 & 2.3

**Comment by Dhan-shri** [comment]
Done changes id's
