### ISSUE TITLE
Meraki Bot chat room not available in the Mentor Tab

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#210]
**Describe the bug**
Meraki Bot chat room is not available in the Mentor Tab.

**To Reproduce**
1. Student taps on the Mentor tab at the bottom of the screen
2. Mentor screen is displayed where the chat rooms for the enrolled courses are shown
3. Meraki Bot chat room is not displayed

**Expected behaviour**
The mentor screen is displayed where the chat rooms for the enrolled courses are shown, along with the Meraki Bot chat room.

**Screencast**
https://drive.google.com/file/d/1MQZr6uHpEkR22B1CW08pb0n9VNiGdNGE/view

**Refer Sheet:**
Student is logged in (app), Test Case 6.1 & 7.1

**Comment by Dhan-shri** [comment]
This will cover up in new feature of chat which is in progress, attaching figma link

**Comment by saquibaijaz** [comment]
@Dhan-shri 
All right
Can you please send me a message on slack informing me about who is working on developing this chat feature?

**Comment by saquibaijaz** [comment]
chat feature removed
