### ISSUE TITLE
Student edits profile and enters an Invalid Name

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#211]
**Describe the bug**
The Invalid Name entered by the student gets saved

**To Reproduce**
1. Tap on the profile tab
2. Enter an Invalid Name (eg. Name containing numbers or special characters) and tap Save
3. The invalid name gets saved

**Expected behaviour**
An error message is shown asking Student to enter a Valid Name

**Screencast**
https://drive.google.com/file/d/1Ma5gsmUme7iqOC-M-MUihm4OyUjcLc8I/view

**Refer Sheet:**
Student is logged in (app), Test Case 9.4

**Comment by Dhan-shri** [comment]
Done
