### ISSUE TITLE
Student leaves the name field blank while editing the Profile

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#212]
**Describe the bug**
A wrong error message is displayed when the student leaves the name field blank and tries to Save the Profile.

**To Reproduce**
1. Tap on the profile tab
2. Erase the name from the name field and leave it blank and tap Save
3. The error message displayed is "Unable to update your profile. Please try again"

**Expected behaviour**
An error message is shown asking the student to enter a name

**Screencast**
https://drive.google.com/file/d/1MaJ503P5TDHGlRXWt9F3aNZs7T0kNIDy/view

**Refer Sheet:**
Student is logged in (app), Test Case 9.5

**Comment by Dhan-shri** [comment]
Done

**Comment by saquibaijaz** [comment]
@Dhan-shri 
It's working fine
