### ISSUE TITLE
(Playground) Student taps on Back button without saving the code

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#223]
**Describe the bug**
The code is lost if the back button is tapped without saving the code

**To Reproduce**
1. Start writing Python code in the playground
2. Without saving the code, tap on the Back button
3. You are taken to the playground area and the unsaved changes are lost

**Expected behaviour**
The student is prompted to save the code before exiting or the changes will not be saved and the work will be lost

**Screencast**
https://drive.google.com/file/d/14Ss7YHNLj_6mEGs3R4u1ZhZqpF2YBrlj/view

**Refer Sheet:**
TestCases for Playground (app), Test Case 17.1

**Comment by Dhan-shri** [comment]
So what are we expecting when the student taps on the back button, can we show any dialog box student like "You want to save the code or not"  @saquibaijaz

**Comment by saquibaijaz** [comment]
@Dhan-shri , see the expected behaviour. There can a dialogue box, or anything that prompts user that the changes will not be saved

**Comment by saquibaijaz** [comment]
@Dhan-shri 
It's working fine
