### ISSUE TITLE
Playground in android (Typing part)

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/soni-sori#281]
1. In the Playground search bar, if the user is finding something that is not available there, the message should show that they have not found something like this.

Device name : vivo Y20G
OS version : Funtouch OS 13 Global
Hardware version : MP_0.1
Model : V2037
Android version : 13

@surajsahani 

![WhatsApp Image 2023-11-28 at 12 34 17 PM](https://github.com/navgurukul/soni-sori/assets/83698383/ca1a9eb1-dbea-4ecc-b156-4663707a4c77)

**Comment by saquibaijaz** [comment]
It only works in internal release or production release and not on debug APKs
