### ISSUE TITLE
In question turm bug 

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/soni-sori#282]
- When the user selects any answer option for any question, if that option is wrong, it should show up in the red box and the correct one in the green box.In some questions, it is correct.

- But in some questions, it is showing only the correct option. Not which we selected before the correct answer, wrong one not showing is red box, only the green box is there.
-

Device name : vivo Y20G
OS version : Funtouch OS 13 Global
Hardware version : MP_0.1
Model : V2037
Android version : 13

@surajsahani 

![WhatsApp Image 2023-11-28 at 12 49 56 PM (1)](https://github.com/navgurukul/soni-sori/assets/83698383/87f109f6-d4f8-4f15-991c-7d2da592dae3)

![WhatsApp Image 2023-11-28 at 12 49 56 PM](https://github.com/navgurukul/soni-sori/assets/83698383/4689c38b-380e-4590-80d1-8b048e2270de)

**Comment by surajsahani** [comment]
Closing this for now, please raised this issues again. when reproducible
