### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/soni-sori#285]
- When user is using app at that time suddenly app geeting crash (Blank).
When user is opeing the app at that time it is talking to much time to open it still sometime it is not able to open.

Device name : vivo Y20G
OS version : Funtouch OS 13 Global
Hardware version : MP_0.1
Model : V2037
Android version : 13

@surajsahani 

![WhatsApp Image 2023-11-27 at 7 38 40 PM](https://github.com/navgurukul/soni-sori/assets/83698383/1c98db29-df66-4767-899b-0c13e8bd0e15)

**Comment by surajsahani** [comment]
@Jayshri15 how we can reproduce it?
