### ISSUE TITLE
Progress bars always 100% (device specific)

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/soni-sori#289]
This issue is only encountered on Samsung Galaxy A14 5G (Android 14)

1. User logs in on the app.
2. Even if the course modules are incomplete, the progress circles are always 100%
3. This issue is not coming on any other devices.

https://github.com/navgurukul/soni-sori/assets/111858763/fb2e7e9d-ee64-482b-bfbc-1ac59869b2c8

**Comment by surajsahani** [comment]
Closing this issue, already fixed and merged
