### ISSUE TITLE
Title: "Interactive Questions Unresponsive: Users Need to Refresh for Functionality"

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/soni-sori#317]
In theMerakilearn section, all courses are getting this problem. When the user answers the question in that question,
some options are not responsive. After refreshing, it's working.
It means some questions are not refreshing.The user has to refresh it and return.

Environment:
Android version 13
Device name : vivo Y20G
Model : V2037
OS version : Funtouch OS 13 Global
@surajsahani

Uploading WhatsApp Video 2024-01-29 at 5.58.41 PM (2).mp4…

**Comment by aayushitiwari03** [comment]
Fixed this issue in mcq_issues/ayushi

**Comment by surajsahani** [comment]
Closing this
