### ISSUE TITLE
Cannot Open New Project in Playground

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/soni-sori#337]
**Issue** :  - Cannot open a newly created project in the Playground.
**Expected** : -  New project should open without issues.
**Actual** :  - New project cannot be opened. 
@surajsahani 

https://github.com/navgurukul/soni-sori/assets/83698383/04af759d-95db-45e9-bf13-de407e46d395

**Comment by surajsahani** [comment]
WenIDE Can only be tested on Internal Release
