### ISSUE TITLE
Class rules not formatted properly

### ISSUE THREAD

**Issue by pysaquib** [navgurukul/soni-sori#44]
To read the full rules, one has to scroll the text to the left. There should be line breaks in appropriate position of the text depending on the device screen size.

**Comment by aashish-aadarsh** [comment]
Details please, with Screenshot

**Comment by abhishekgupta92** [comment]
Rules shouldn't have horizontal scroll and should wrap.

**Comment by aashish-aadarsh** [comment]
The rules are rendered using markdown syntax. This can be controlled from backend.

**Comment by aashish-aadarsh** [comment]
Will be done from server side

**Comment by abhishekgupta92** [comment]
![Screenshot_20201016-163940.jpg](https://user-images.githubusercontent.com/1681009/96251651-68270780-0fce-11eb-9d85-aa84ffba96c2.jpg)

The issue still persists. Let's all debug this together for a smoother coordination between backend and frontend

@pysaquib and @aashish-aadarsh

**Comment by pysaquib** [comment]
Fixed from server side. Closing this
