### ISSUE TITLE
Classes UI

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/soni-sori#57]
Classes UI is significantly different than the one that has been implemented. It needs to be updated. 
![image](https://user-images.githubusercontent.com/1681009/96250323-4c226680-0fcc-11eb-914d-129dc48437d4.png)

- [x] The underscore needs to be removed from doubt_class in sync with backend on this.

- [x] For the same date, the slots are being divided into two dates
![image](https://user-images.githubusercontent.com/1681009/97703101-0d190880-1ad6-11eb-969c-6a9c106b95c5.png)

- [x] Add time range for the class, as students need it to decide which classes should they enroll to. 

- [x] Time format should be 12 hour format across the classes UI.

**Comment by suhaibroomy** [comment]
Should we maybe move this to a different screen, right now we just change the contents in the same screen and its not very intuitive to go back

**Comment by abhishekgupta92** [comment]
Do you mean adding a new tab altogether or you are talking about a technical feature? Waise, I see limited use of home screen until we have built better views/data. It looks like classes should be accessible directly from the screen instead of the current approach. Maybe we can add a screen for it instead.

**Comment by suhaibroomy** [comment]
In the screenshot you posted above, this is a different screen altogether, with a back button for user to go back. What we do in the app is just switch the contents of home screen (i.e user still sees all the tabs and can navigate to other tabs). So its not very intuitive for user that they have left home screen and and are looking at something else. There is no back button for users to go back to the previous state (i.e flip the contents back to what it was). I was just wondering if we should do what is in the design

**Comment by suhaibroomy** [comment]
I agree, it makes sense to atleast display 2-3 upcoming classes on home screen and then display all of them in the another screen

**Comment by abhishekgupta92** [comment]
Agree. This is the least that should be done.
