### ISSUE TITLE
Multilingual flag needs to be updated using Remote Config of firebase.

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/soni-sori#58]
As per the design - https://www.figma.com/file/XxhFD4jLP6pTx9Eq6B8Bm4/Design-Handoff?node-id=820%3A1315

We need to enable the multilingual feature for the application.

**Comment by aashish-aadarsh** [comment]
What is the importance of remote config in said screen ? To show the available langugage ??

**Comment by suhaibroomy** [comment]
@aashish-aadarsh yes we decided to fetch list of languages from config instead of getting them from server to reduce number of calls to server

**Comment by abhishekgupta92** [comment]
Yes!
