### ISSUE TITLE
Default Profile Picture 

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/soni-sori#69]
Default profile picture that of Android phone is of a dolphin, while it should get the profile picture URL from the user object and use it instead.[]()![Screenshot_20201018-170510.jpg](https://user-images.githubusercontent.com/1681009/96366279-4d869700-1164-11eb-8955-6c0008e6a37f.jpg)

**Comment by suhaibroomy** [comment]
What do we display in case the profile picture is empty?

**Comment by abhishekgupta92** [comment]
Can we have that default url through remote config? What's the suggested
practice on this?

**Comment by suhaibroomy** [comment]
The default practice is to have an avatar as placeholder included in the app. We can also do remote config though.

**Comment by abhishekgupta92** [comment]
@suhaibroomy - Perfect!

Use this for default avatar : https://drive.google.com/drive/folders/12v0D3Ika78d-qFjnxLXmd1MZZlDJ-W4F?usp=sharing

Also, the avatar should be rendered from the user object.
