### ISSUE TITLE
Course & Pathway Progress (Designs already done)

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/soni-sori#98]
All pathways and courses should have progress notion. Please suggest whatever changes should be made in API to support that.

**Comment by aashish-aadarsh** [comment]
@abhishekgupta92 , can you please share the figma screenshot for this ?

**Comment by abhishekgupta92** [comment]
1. [Course Progress](https://www.figma.com/file/XxhFD4jLP6pTx9Eq6B8Bm4/Design-Handoff?node-id=698%3A1334)

2. [Pathway Progress](https://www.figma.com/file/CamSZaWwqWRBMNyiuAh7Xh/Meraki-app-(Source)?node-id=119%3A1338)
- Completed Courses
- Ongoing Courses
- Courses where I have not enrolled at would be grayed out

**Comment by aashish-aadarsh** [comment]
1. How to determine the percentage of course ?
2. How to determine if course is completed ?

**Comment by pysaquib** [comment]
1. A course is completed when all of its exercises are completed.
2. You have the API, GET /courses/complete to get a list of all completed courses. Same is for exercises and pathways.

**Comment by saquibaijaz** [comment]
Progress bars implemented
